meson: Do not use global arguments when subproject
gul-cpp/gul14 pull request #56
Opened 2023-06-19 15:03 UTC by soerengrunewald

When we use libgul as subproject the setup will fail with:
> ERROR: Function 'add_global_arguments' cannot be used in subprojects because there is no way to make that reliable.

Fixes: 114b594a821 (meson: Enable extra warnings by default)

2023-06-19 15:38 UTC, alt-graph approved these changes
Ouch! Yes, makes sense. :+1:

2023-06-20 05:14 UTC, Finii requested changes
Well...

Unfortunately I did not notice the previous PR (the one that is fixed by this one):

![image](https://github.com/gul-cpp/gul14/assets/16012374/ab706a1e-ab70-45b7-8100-cd5bf2bdc06e)
 
I already have a problem with THAT, and the change in this PR does not make it any better.

### First issue

Why do you add `-Wshadow` as global argument? It **is already there**, right? Is this some kind of doppelt genaeht haelt besser?

https://github.com/gul-cpp/gul14/blob/114b594a821baf17638e71604a31f55b472918eb/src/meson.build#L95-L100

### Second issue

Why do you assume all compilers on all platforms apart from Windows support the options?
`if host_machine.system() != 'windows'` and `Both GCC and clang know how to handle these options` are orthogonal and have nothing to do with each other?
Better would be to check the availability on configure time, like, see code snippet above.

----

So why do you add the at all? Is that feature not working on your platform?
It does work on mine. Here I check out before the original change.

```
$ git checkout 866ee07ca14b
$ make mrproper
$ meson setup build
$ ninja -vC build
```

![image](https://github.com/gul-cpp/gul14/assets/16012374/f629d36f-7642-4852-96e0-6b2678903430)

**Edit:**

Relevant commits:

b75ac9d `Revert "meson: Allow custom warning lvl with old meson"`
87b1c22 `meson: Re-enable shadow warning`
4f8054d `meson: Enable conversion warning`

The last commit is even co-authored by you and has the same commit message as the change introduced by this global stuff (?!)

2023-06-20 05:34 UTC, Finii commented
And BTW, this is **still** broken, despite Lars' intervention in the other PR:

![image](https://github.com/gul-cpp/gul14/assets/16012374/9d31b00f-e374-44cd-b8fb-3911bffb013b)

2023-06-20 08:03 UTC, Finii approved these changes
🎉

2023-06-20 10:46 UTC, merged