Meson: Honor "default_library" option
gul-cpp/gul14 pull request #96
Opened 2024-11-27 14:54 UTC by alt-graph

# [why]
So far, we always provided build targets for both the static and the
shared library in our build script. This did not allow users to simply
select their desired library type via the standard "default_library"
option.
    
# [how]
Set a project default of "default_library=both" and provide the shared
and static library build targets only if they are part of the
user-selected "default_library" option.

2024-11-27 15:59 UTC, soerengrunewald requested changes

2024-11-27 15:59 UTC, soerengrunewald commented on src/meson.build
> +    libgul = shared_library(
In case one configures with `--default-library static`, the object `libgul` is not available. And so the `pkg.generate(` at line 134 will fail.

2024-11-29 08:54 UTC, Finii requested changes
I do not see where this addresses the "problem" at all.
Maybe I'm blind.

I guess there is a misunderstanding what default_library does. It does usually NOT influence what is built.

Even with this PR the user still needs to select either libgul_dep (for dynamic) or libgul_static_dep (for static) for the desired library type.

default_library should enable you to select which library type is used ON THE FLY without editing any file, just as Meson configure time option.

In principle you have something like

libgul_static_or_dynamic_dep = both_libraries( ... )

And THAT dependency object, which usually contains BOTH libraries, which you can select explicitely still; if you use that without specifying explicitely what you wants follows the default_library setting.

This whole PR has nothing to do with `default_library` except it misuses it to not build one type or the other.

2024-11-29 09:16 UTC, Finii commented
I guess this change has been triggered by George's email?

And he is right, we should probably use `library()` instead of what we use now. Iirc there was no such function when we started with GUL, but maybe I'm wrong.

With `library` you can 

```
newlibgul_dep = library(
    ....
    cpp_shared_args : add_cpp_args + [ '-DGUL_COMPILING_SHARED_LIB' ],
    cpp_static_args : add_cpp_args + [ '-DGUL_USING_STATIC_LIB_OR_OBJECTS' ],
)
```

But of course we break dependents if we touch `libgul_dep` (which would be the 'right' name) and have it return something not being the shared library always. That's the reason for the `new` name above.

But then, having established already the two fixed-type dependency variables, what do we really gain? Is it really so important to support `default_library`? :thinking: I have the feeling the use case is very very limited.

2024-11-29 13:48 UTC, alt-graph commented
> This whole PR has nothing to do with `default_library` except it misuses it to not build one type or the other.

I am confused. https://mesonbuild.com/Build-targets.html states this:

> It is generally preferred to use the `library` command instead of `shared_library` and `static_library` and then configure which libraries (static or shared or both of them) will be built at the build configuration time using the `default_library` built-in option.

Isn't this exactly what `default_library` is about? To provide a generic way of configuring from the outside which kind of library is built by a project when you just run `meson compile` without having to know the specific targets inside the project?

2024-11-29 13:54 UTC, alt-graph commented
BTW This would also make the packaging for `vcpkg` smoother: At the moment, the package manager makes a default build (which builds both libraries), and afterwards our port has to remove the unwanted (static/shared) version of the library.

2024-12-02 08:36 UTC, soerengrunewald commented
To my understanding this PR aims to simulate the behavior of `library` for older meson version. 
It is a hack, indeed. But it allows the user to request whether to build a static or a shared library or both. Which is something we can not at the moment, since we simply ignore the request.

Yes, we have a problem with the dependency variables. But we would need to solve this anyhow as soon as we start using `library`. Since there we would also have only one variable.

So it is a hack. But one that improves our situation in a sense. By now we have to decide in the wrap file if we wanna link dynamically or statically. With this change we can pass the wish done to the subproject.

E.g for pydoocs we specify the following:
```ini
[provide]
dependency_names = libgul14
libgul14 = libgul_static_dep
```
To ensure we link the subproject statically.

With the change we can pass it just as argument:
```bash
meson setup --wrap-mode forcefallback --Dlibgul14:default-library static ...
```

2024-12-02 12:28 UTC, Finii commented
Ok, lets forget my confused comments from last week ;-)

### Change type

I believe this is a breaking change, as the contents of `libgul_dep` can now contain a static dependency, which was not possible before. One could argue that the person who uses this must have selected the static lib to be in that dependency, so this is probably not really breaking.

### Stub for replacement

I further think that, if we want to substitute some modern-Meson stuff into old `meson.build` files,
* we should only do this if there are severe reasons. We had similar things in the past and always kept back changes until we could finally change the required Meson version instead of having brand new features.
* we should use the new feature if the Meson version is sufficient! This makes sure we really understand the feature.
* this makes it easier to finally drop the kludge when we expect more modern Mesons, and we do not forget to drop it

For example this
```python
if meson.version().version_compare('>=0.53')
   summary({'prefix': get_option('prefix'),
           }, section: 'Directories')
   summary({'EPICS Support': epics_dep.found(),
            'TINE Support': libtine_dep.found(),
           }, section: 'Configuration')
endif
```
In that case we do not emulate the new feature.

### Trying to make it work

I have this code added:

```python
## Static and shared libraries

libgul = library(
        meson.project_name(),
        sources : libgul_src + [ version_cc ],
        cpp_static_args : add_cpp_args + [ '-DGUL_USING_STATIC_LIB_OR_OBJECTS' ],
        cpp_shared_args : add_cpp_args + [ '-DGUL_COMPILING_SHARED_LIB' ],
        dependencies : deps,
        include_directories : inc,
        soversion : so_version,
        gnu_symbol_visibility : 'hidden',
        install : true
)
```

But then I struggle to create the `libgul*_dep` variables.
The object within `libgul` is one of `SharedLibraryHolder`, `BothLibrariesHolder`, or `StaticLibraryHolder`; but there is no closed way (that I see) how one can access this in a sane manner. No test-ability (cast to bool). We have to fall back and parse (?!) the `default-library` argument string-wise and then use maybe the member method `get_static_lib()` etc. :sob: 

I do not really see how we are supposed to create the `*_dep` variable if we used `library()` _**at all**_. Using `declare_dependency()` with parsing? This can not be the idea behind it. And also, where is mentioned that `both` means prefer `shared` for subprojects?

This is my complete (tested) example for after-1.3.0-Meson

```python
## Static and shared libraries

libgul = library(
    meson.project_name(),
    sources : libgul_src + [ version_cc ],
    cpp_static_args : add_cpp_args + [ '-DGUL_USING_STATIC_LIB_OR_OBJECTS' ],
    cpp_shared_args : add_cpp_args + [ '-DGUL_COMPILING_SHARED_LIB' ],
    dependencies : deps,
    include_directories : inc,
    soversion : so_version,
    gnu_symbol_visibility : 'hidden',
    install : true
)


_compile_args = []
if get_option('default_library') == 'both'
    _libgul_lib = libgul.get_shared_lib()
else
    _libgul_lib = libgul
    if get_option('default_library') == 'static'
        _compile_args = [ '-DGUL_USING_STATIC_LIB_OR_OBJECTS' ]
        message('libgul_dep setup for static linking')
    endif
endif

libgul_dep = declare_dependency(
    dependencies : deps,
    include_directories : inc,
    link_with : _libgul_lib,
    compile_args : _compile_args,
)
```

And then the pkgconfig file is still unsolved.

### Thoughts

I think there is no gradual movement from the old 'we have two dependency variables' to the 'static or shared is decided via user option' method, despite the efforts here. If we really want to switch I would switch completely, which means there is no `libgul_static_dep` anymore - you express that through `--Dlibgul14:default-library static`.

So, my point is, we should look and implement this with `library()` (Meson 1.3.0) first and see how that behaves and then add portability code on top for older Mesons. If not we may run into a situation where the "solution" is still incompatible / not optimal / kludgy with modern `library()` of 1.3.0 and we still are not 'canonical' after 1.3.0.

A bit of research is missing here, for example how other people use 1.3.0's `library()` together with subproject variables.
But it took already incredible amounts of time for a "unneeded" change, just because someone says we are not HEAD of Meson modern - which we never were and never strove to be. Rather we tried to keep all the meson files as uncomplex as possible and that already failed, but is adding more and more "Meson backports" good anyhow? Or wait until all platforms are on 1.3.0+ (i.e. Ubuntu 24.04) and change only then?

This raises multiple questions is my feeling.

2024-12-06 15:25 UTC, alt-graph commented on data/doxygen.h
> + * - *Released with DOOCS 24.10.0-24.11.0*
I have updated the formatting a little and fixed the 24.1.0 entry.

2024-12-06 15:35 UTC, alt-graph commented
I am not sure if I understand all the fine details here. Probably not. But let me ask this as an absolute layman in Meson terms:
- This PR allows us to build static, shared, or both libs via the `default_library` mechanism, right?
- The changes in this PR work with old Meson versions. We claim 0.49, right?
- Whose build do we break if we apply the changes as-is in this PR?

2024-12-09 07:30 UTC, Finii commented
Also just ignoring what you wrote and repeating some of the points already detailed above:

* Implement the stuff with modern (i.e. 1.3.0+) stanza and then add meson.version dependent 'backports' that can be much more easily removed once we advance the required Meson version
* Support either the classic 'one variable for static one for shared' or 'one variable for both' and not a mix that has shortcoming in both scenarios. I have nothing against dropping the two-variables scheme
* I am not sure if the 'one variable for both' scheme does really work for what we want to do, but that is lack of my knowledge.
* One problems is that it seems impossible to runtime-check if the variable is a 'BothLibrariesHolder' or a Holder for just one variant. It's rather hard to come up with nice error messages if the user requests one specific type while we demand via dependencies another one. Maybe it's a "just your fault, think before you do" case, but then, what was your argument in some other place: Make it easy to use right and hard to use wrong. The addition if this feature (this PR) without the possibility to runtime checks makes it easier to get obscure problems (that we can not diagnose for the user), and we gain in principle nothing.
* Yes, I see no real gain in this. All you can do with the `default-library-type` thing you can also do with the classic two variable solution only maybe not as convenient. But we would add more (undiagnosable, see above) error sources that people can shoot into their foot with.

2024-12-09 14:39 UTC, soerengrunewald commented
I think the main dissent here is whether we need/care about the dependency objects or not.

I personally don't care much about `libgul_[static_]dep`. As I much rather prefer to relay on pkg-config, as it is (at lease for me) more transparent in its behavior. To me the dependency objects should be project internal only. And other (sub)projects should not rely on them at all. But maybe I'm just to old and inflexible to see the beauty of the dependency objects :wink:

That been said, a cleaner approach, which is more in line with the upstream recommendations, is of course preferable. But I don't see how this could actually work. Since at leased for the moment, we are stuck with meson 0.53.2. This means `library` does not know about `cpp_shared_args` or `cpp_static_args`. Which in return means you can not use it with 0.53.2 in the suggested way to build both libraries. That is why we split it up in first place  (see 0b8b5c590). And in order to make it at lease somewhat work, you'll have to prepare the compiler arguments first, as there is only one ingestion point `cpp_args`:
```meson
_compile_args = []
if meson.version().version_compare('<1.3')
    if get_option('default_library') == 'static'
        _compile_args += '-DGUL_USING_STATIC_LIB_OR_OBJECTS'
    else
        _compile_args += '-DGUL_COMPILING_SHARED_LIB'
    endif
endif

libgul = library(
    meson.project_name(),
    sources : libgul_src + [ version_cc ],
    cpp_args :  [ add_cpp_args + _compile_args ],
    # this will probably generated warnings/errors with < 1.3.0
    cpp_static_args : add_cpp_args + [ '-DGUL_USING_STATIC_LIB_OR_OBJECTS' ],
    cpp_shared_args : add_cpp_args + [ '-DGUL_COMPILING_SHARED_LIB' ],
    dependencies : deps,
    include_directories : inc,
    soversion : so_version,
    gnu_symbol_visibility : 'hidden',
    install : true
)
if meson.version().version_compare('<1.3')
    if get_option('default_library') == 'both'
       _libgul_lib = libgul.get_shared_lib()
    else
       _libgul_lib = libgul
       if get_option('default_library') == 'static'
           message('libgul_dep setup for static linking')
       endif
    endif
endif

libgul_dep = declare_dependency(
    dependencies : deps,
    include_directories : inc,
    link_with : _libgul_lib,
    compile_args : _compile_args,
)

# TODO: pkg-config stuff
```

And this IMO makes thinks probably more cluttered than the proposed PR.

2024-12-12 09:01 UTC, Finii commented
@soerengrunewald Unfortunately you code will not work, because `library()` before 1.3 compiles the stuff only once and from the object files creates both the static and the dynamic library. The special static flags are added anyhow only when build-only-a-static-lib is selected.

----

For me the question is, what would we want to have finally. If we have Meson 1.6.99 (as I do).

If we drop the static dependency variable to be more modern, we end probably up with something like this:

```python
deps = dependency('threads')

libgul = library(
    meson.project_name(),
    sources : libgul_src + [ version_cc ],
    cpp_args :  add_cpp_args,
    cpp_static_args : '-DGUL_USING_STATIC_LIB_OR_OBJECTS',
    cpp_shared_args : '-DGUL_COMPILING_SHARED_LIB',
    dependencies : deps,
    include_directories : inc,
    soversion : so_version,
    gnu_symbol_visibility : 'hidden',
    install : true
)
libgul_dep = declare_dependency(
    dependencies : deps,
    include_directories : inc,
    link_with : libgul,
)

pkg = import('pkgconfig')
pkg.generate(
    libgul,
    libraries : [ '-Wl,-rpath,${libdir}' ],
    name : 'lib' + meson.project_name(), # This is in fact wrong (but usually correct)
    description : 'General Utility Library',
    version : '@0@'.format(libgul_api_version)
)

# vi:ts=4:sw=4:sts=4:et:syn=conf
```

_Note to self: Why the `@0@` in the pkgconfig version? And is the `GUL_USING_STATIC_LIB_OR_OBJECTS` added in the pkgconfig file? I believe it must be added to the static cflags_ :thinking: 

Starting from our goal I would add some backport stuff, that might look cluttered, but it will be dropped somewhen anyhow. Maybe something like this: (Which is ... more cluttered, but the backport stuff is readily visible)

```python
deps = dependency('threads')         
                                     
if meson.version().version_compare('>=1.3')  
    message('Using modern stuff')    
    libgul = library(                
        meson.project_name(),        
        sources : libgul_src + [ version_cc ],  
        cpp_args :  add_cpp_args,    
        cpp_static_args : '-DGUL_USING_STATIC_LIB_OR_OBJECTS',  
        cpp_shared_args : '-DGUL_COMPILING_SHARED_LIB',  
        dependencies : deps,         
        include_directories : inc,   
        soversion : so_version,      
        gnu_symbol_visibility : 'hidden',  
        install : true               
    )                                
else                                 
    if get_option('default_library') in ['both', 'static']  
        libgul = static_library(     
            meson.project_name(),    
            sources : libgul_src + [ version_cc ],  
            cpp_args : add_cpp_args + [ '-DGUL_USING_STATIC_LIB_OR_OBJECTS' ],  
            dependencies : deps,     
            include_directories : inc,  
            install : true           
        )                            
    endif                            
    if get_option('default_library') in ['both', 'shared']  
        libgul = shared_library(     
            meson.project_name(),    
            sources : libgul_src + [ version_cc ],  
            soversion : so_version,  
            cpp_args : add_cpp_args + [ '-DGUL_COMPILING_SHARED_LIB' ],  
            dependencies : deps,     
            include_directories : inc,  
            gnu_symbol_visibility : 'hidden',  
            install : true           
        )                            
    endif                            
endif                                
                                     
libgul_dep = declare_dependency(     
    dependencies : deps,             
    include_directories : inc,       
    link_with : libgul,              
)                                    
                                     
pkg = import('pkgconfig')            
pkg.generate(                        
    libgul,         
```

We could easily 'break' the `libgul_static_dep` thing away with the change to gul17 ;-D
The question is, do we need it. Probably for `pydoocs` (only), but otoh, maybe we can achieve that there also with `default_lib=static`.

2024-12-13 15:16 UTC, soerengrunewald commented
> @soerengrunewald Unfortunately you code will not work, because `library()` before 1.3 compiles the stuff only once and from the object files creates both the static and the dynamic library. The special static flags are added anyhow only when build-only-a-static-lib is selected.

I just notice, that `-DGUL_USING_STATIC_LIB_OR_OBJECTS` and `-DGUL_COMPILING_SHARED_LIB` are actually only relevant for WINDOWS and who cares about that :thinking: So we do this all just to make windows happy, right?

2025-02-28 14:40 UTC, alt-graph commented
I consider this rejected for GUL14, but we may yet pick it up for GUL17.

2025-02-28 14:40 UTC, closed without merging